export PATH=$HOME/local/bin:/usr/local/bin:$PATH

##########
# ALIASES
##########

# Programs

# MySQL

alias mysql=/usr/local/mysql/bin/mysql
alias mysqld=/usr/local/mysql/bin/mysqld_safe
alias mysqladmin=/usr/local/mysql/bin/mysqladmin

# Code Monkey Upstairs VPS
cmu="192.34.60.223"
alias cmu@cmu="ssh cmu@$cmu"
alias kyle@cmu="ssh kyle@$cmu"
alias root@cmu="ssh root@$cmu"

# Brewmaster VPS
brewmaster="192.241.196.22"
alias root@brewmaster="ssh root@$brewmaster"
alias api@brewmaster="ssh api@$brewmaster"

# Reload profile
alias reload="source ~/.bash_profile"

# Hide / Show Files
alias showFiles='defaults write com.apple.finder AppleShowAllFiles YES; killall Finder /System/Library/CoreServices/Finder.app'
alias hideFiles='defaults write com.apple.finder AppleShowAllFiles NO; killall Finder /System/Library/CoreServices/Finder.app'

# fucking Xcode
# http://www.mikeash.com/pyblog/solving-simulator-bootstrap-errors.html
alias xcode-unfuck-bootstrap="launchctl list|grep UIKitApplication|awk '{print $3}'|xargs launchctl remove"

# http://inessential.com/2012/04/23/ded
alias xcode-unfuck-deriveddata="rm -rf ~/Library/Developer/Xcode/DerivedData"

############
# UTILITIES
############

# Rename tab
function tabname {
  printf "\e]1;$1\a"
}

# Rename window
function winname {
  printf "\e]2;$1\a"
}
