"" ----RESOURCES---
"" http://stevelosh.com/blog/2010/09/coming-home-to-vim/

"" ----PLUGINS----

execute pathogen#infect()

"" Filetype
filetype on
filetype plugin on

"" NERDTree
silent! nmap <F2> :NERDTreeToggle<CR>
silent! map <F3> :NERDTreeFind<CR>

let g:NERDTreeMapActivateNode="<F3>"
let g:NERDTreeMapPreview="<F4>"
let g:NERDTreeWinSize=40

"" ----SETTINGS----

"" Map Leader
let mapleader=','

"" Aesthetics
colorscheme Tomorrow-Night
set lbr
set number
syntax on

"" Wrapping
set colorcolumn=85
set formatoptions=qrn1
set textwidth=79
set wrap

"" Tabs and Indents
set autoindent
set backspace=indent,eol,start
set expandtab
set shiftwidth=4
set softtabstop=4
set tabstop=4

"" Search Taming
nnoremap / /\v
vnoremap / /\v
set ignorecase
set smartcase
set gdefault
set incsearch
set showmatch
set hlsearch
nnoremap <leader><space> :noh<cr>

"" General Specialty Stuff
au FocusLost * :wa
set cursorline
set encoding=utf-8
set hidden
set laststatus=2
set modelines=0
set nocompatible
set ruler
set scrolloff=3
set showmode
set showcmd
set ttyfast
set undofile
set visualbell
set wildmenu
set wildmode=list:longest

"" Disable auto-commenting lines
autocmd FileType * setlocal formatoptions-=c formatoptions-=r formatoptions-=o

"" ----MAPPINGS----

"" Insert new lines
map <Enter> o<ESC>
map <S-Enter> O<ESC>

"" Jump real lines, not virtual 
nnoremap j gj 
nnoremap k gk
xnoremap j gj
xnoremap k gk

"" Fast jumping
nmap J 5j 
nmap K 5k
xmap J 5j
xmap K 5k

"" Bracket jumping
nnoremap <tab> %
vnoremap <tab> %

"" Center lines when jumping
nnoremap gg ggz.

"" Splits, easier 
map <leader>w- <C-W>- 
map <leader>w+ <C-W>+ 
map <leader>w[ <C-W>= 
map <leader>w] <C-W>_ 

"" Move between splits
nmap gh <C-w>h
nmap gj <C-w>j
nmap gk <C-w>k
nmap gl <C-w>l

"" Force HJKL
nnoremap <up> <nop>
nnoremap <down> <nop>
nnoremap <left> <nop>
nnoremap <right> <nop>
inoremap <up> <nop>
inoremap <down> <nop>
inoremap <left> <nop>
inoremap <right> <nop>
nnoremap j gj
nnoremap k gk
