" vim configuration

" --- Plugins ---

" Load Pathogen for plugin management.
source ~/.vim/bundle/vim-pathogen/autoload/pathogen.vim
execute pathogen#infect()

" Enable filetype detection and plugins.
filetype on
filetype plugin on
filetype indent on

" NERDTree file explorer.
silent! nmap <F2> :NERDTreeToggle<CR>
silent! map <F3> :NERDTreeFind<CR>

let g:NERDTreeMapActivateNode="<F3>"
let g:NERDTreeMapPreview="<F4>"
let g:NERDTreeWinSize=40

" --- Settings ---

" Map leader key to comma.
let mapleader=','

" Appearance
colorscheme solarized
set background=dark
set cursorline
set lbr
set number
set showcmd
syntax enable

" Line wrapping at 120 characters.
set colorcolumn=120
set formatoptions=qrn1
set textwidth=120

" Tabs and indentation
set autoindent
set backspace=indent,eol,start
set expandtab
set shiftwidth=4
set softtabstop=4
set tabstop=4

" Search behavior
nnoremap / /\v
vnoremap / /\v
set ignorecase
set smartcase
set gdefault
set incsearch
set showmatch
set hlsearch
nnoremap <leader><space> :nohlsearch<cr>

" General settings
au FocusLost * :wa              " Save on focus lost.
set encoding=utf-8
set hidden
set laststatus=2
set lazyredraw
set modelines=0
set nocompatible
set ruler
set scrolloff=3
set showmode
set showcmd
set splitright
set ttyfast
set undofile
set visualbell
set wildmenu
set wildmode=list:longest

" Backup configuration
set backup
set backupdir=~/.vim-tmp,~/.tmp,~/tmp,/var/tmp,/tmp
set backupskip=/tmp/*,/private/tmp/*
set directory=~/.vim-tmp,~/.tmp,~/tmp,/var/tmp,/tmp
set writebackup

" Disable automatic comment continuation.
autocmd FileType * setlocal formatoptions-=c formatoptions-=r formatoptions-=o

" --- Key Mappings ---

" Use jk to escape insert mode.
inoremap jk <esc>

" Insert blank lines without entering insert mode.
map <Enter> o<ESC>
map <S-Enter> O<ESC>

" Navigate wrapped lines naturally.
nnoremap j gj 
nnoremap k gk
xnoremap j gj
xnoremap k gk

" Jump 5 lines at a time with J/K.
nmap J 5j 
nmap K 5k
xmap J 5j
xmap K 5k

" Tab key jumps between matching brackets.
nnoremap <tab> %
vnoremap <tab> %

" Auto-close brackets and quotes.
inoremap ( ()<Esc>:call BC_AddChar(")")<CR>i
inoremap { {<CR>}<Esc>:call BC_AddChar("}")<CR><Esc>kA<CR>
inoremap [ []<Esc>:call BC_AddChar("]")<CR>i
inoremap " ""<Esc>:call BC_AddChar("\"")<CR>i

" Jump out of brackets with Ctrl-j.
inoremap <C-j> <Esc>:call search(BC_GetChar(), "W")<CR>a

function! BC_AddChar(schar)
    if exists("b:robstack")
        let b:robstack = b:robstack . a:schar
    else
        let b:robstack = a:schar
    endif
endfunction

function! BC_GetChar()
    let l:char = b:robstack[strlen(b:robstack)-1]
    let b:robstack = strpart(b:robstack, 0, strlen(b:robstack)-1)
    return l:char
endfunction

" Use relative line numbers in normal mode, absolute in insert mode.
:au FocusLost * :set number
:au FocusGained * :set relativenumber

autocmd InsertEnter * :set number
autocmd InsertLeave * :set relativenumber

function! NumberToggle()
    if(&relativenumber == 1)
        set number
    else
        set relativenumber
    endif
endfunc

nnoremap <C-n> :call NumberToggle()<cr>

" Center cursor when jumping to top of file.
nnoremap gg ggz.

" Window resizing shortcuts.
map <leader>w- <C-W>- 
map <leader>w+ <C-W>+ 
map <leader>w[ <C-W>= 
map <leader>w] <C-W>_ 

" Navigate between splits with g + hjkl.
nmap gh <C-w>h
nmap gj <C-w>j
nmap gk <C-w>k
nmap gl <C-w>l

" Disable arrow keys to encourage hjkl usage.
nnoremap <up> <nop>
nnoremap <down> <nop>
nnoremap <left> <nop>
nnoremap <right> <nop>
inoremap <up> <nop>
inoremap <down> <nop>
inoremap <left> <nop>
inoremap <right> <nop>
nnoremap j gj
nnoremap k gk